apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: localdemo-index
spec:
  type: url
  targets:
    - https://github.com/iorlas/backstage-wip/blob/main/catalog-info.pattern.yaml
    - https://github.com/iorlas/backstage-wip/blob/main/catalog-info.pattern-version.yaml
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: localdemo-index
  description: |
    Backstage is an open-source developer portal that puts the developer experience first.
  annotations:
    github.com/project-slug: backstage/backstage
    backstage.io/techdocs-ref: dir:.
    lighthouse.com/website-url: https://backstage.io
spec:
  type: library
  owner: CNCF
  lifecycle: experimental
